-- Create table Appointments
CREATE TABLE public.appointments (
    id               BIGINT      NOT NULL,
    doctor_id        BIGINT      NOT NULL,
    user_id          BIGINT      NOT NULL,
    appointment_date DATE        NOT NULL,                   -- ngày khám
    appointment_time TIME        NOT NULL,                   -- giờ khám (theo khung giờ cố định)
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED')),
    created_at       TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Auto-increment id
ALTER TABLE public.appointments
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Primary key
ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);

-- FK tới accounts (bác sĩ)
ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk_appointment_doctor FOREIGN KEY (doctor_id)
    REFERENCES public.accounts(id)
    ON DELETE CASCADE;

-- FK tới accounts (bệnh nhân)
ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk_appointment_user FOREIGN KEY (user_id)
    REFERENCES public.accounts(id)
    ON DELETE CASCADE;

-- Ràng buộc không cho 1 bác sĩ có 2 lịch hẹn cùng ngày và giờ
ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT uq_doctor_date_time UNIQUE (doctor_id, appointment_date, appointment_time);
