-- Create table Notifications
CREATE TABLE public.notifications (
    id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    type VARCHAR(50) NOT NULL CHECK (type IN (
        'APPOINTMENT_PENDING',
        'APPOINTMENT_SUCCESS',
        'APPOINTMENT_CANCEL',
        'APPOINTMENT_CHANGED',
        'APPOINTMENT_REVIEW_REQUEST'
        )),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Auto-increment id
ALTER TABLE public.notifications
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Primary key
ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

-- FK tới accounts (người nhận)
ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk_notification_user FOREIGN KEY (user_id)
    REFERENCES public.accounts(id)
    ON DELETE CASCADE;