ALTER TABLE public.keys
DROP COLUMN IF EXISTS notification_key;

-- Create table Device Tokens
CREATE TABLE public.device_tokens (
    id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    fcm_token VARCHAR(512) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Auto-increment id
ALTER TABLE public.device_tokens
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Primary key
ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_pkey PRIMARY KEY (id);

-- FK tới accounts (user sở hữu token)
ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT fk_device_token_user FOREIGN KEY (user_id)
    REFERENCES public.accounts(id)
    ON DELETE CASCADE;
