-- Create table Doctor_Reviews
CREATE TABLE public.doctor_reviews (
    id BIGINT NOT NULL,
    appointment_id BIGINT NOT NULL UNIQUE, -- mỗi appointment chỉ có 1 review
    doctor_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Auto-increment id
ALTER TABLE public.doctor_reviews
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctor_reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Primary key
ALTER TABLE ONLY public.doctor_reviews
    ADD CONSTRAINT doctor_reviews_pkey PRIMARY KEY (id);

-- FK tới appointments (mỗi appointment chỉ có 1 review)
ALTER TABLE ONLY public.doctor_reviews
    ADD CONSTRAINT fk_review_appointment FOREIGN KEY (appointment_id)
    REFERENCES public.appointments(id)
    ON DELETE CASCADE;

-- FK tới accounts (bác sĩ)
ALTER TABLE ONLY public.doctor_reviews
    ADD CONSTRAINT fk_review_doctor FOREIGN KEY (doctor_id)
    REFERENCES public.accounts(id)
    ON DELETE CASCADE;

-- FK tới accounts (bệnh nhân)
ALTER TABLE ONLY public.doctor_reviews
    ADD CONSTRAINT fk_review_user FOREIGN KEY (user_id)
    REFERENCES public.accounts(id)
    ON DELETE CASCADE;