-- Create table Doctor_Detail
CREATE TABLE public.doctor_details (
    id BIGINT NOT NULL,
    specialization VARCHAR(100) NOT NULL,
    experience_years INT NOT NULL DEFAULT 0,
    gender VARCHAR(10) CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    date_of_birth DATE,
    avatar_url VARCHAR(255),
    phone VARCHAR(20),
    bio TEXT,
    user_id BIGINT UNIQUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Auto-increment id
ALTER TABLE public.doctor_details
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctor_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Primary key
ALTER TABLE ONLY public.doctor_details
    ADD CONSTRAINT doctor_details_pkey PRIMARY KEY (id);

-- Foreign key tới accounts
ALTER TABLE ONLY public.doctor_details
    ADD CONSTRAINT fk_doctor_account FOREIGN KEY (user_id)
    REFERENCES public.accounts(id)
    ON DELETE CASCADE;

-- Create table Favorite_Doctors
CREATE TABLE public.favorite_doctors (
    id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Auto-increment id
ALTER TABLE public.favorite_doctors
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_doctors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Primary key
ALTER TABLE ONLY public.favorite_doctors
    ADD CONSTRAINT favorite_doctors_pkey PRIMARY KEY (id);

-- FK tới accounts (user bệnh nhân)
ALTER TABLE ONLY public.favorite_doctors
    ADD CONSTRAINT fk_favorite_user FOREIGN KEY (user_id)
    REFERENCES public.accounts(id)
    ON DELETE CASCADE;

-- FK tới accounts (bác sĩ)
ALTER TABLE ONLY public.favorite_doctors
    ADD CONSTRAINT fk_favorite_doctor FOREIGN KEY (doctor_id)
    REFERENCES public.accounts(id)
    ON DELETE CASCADE;

-- Tránh trùng user - doctor
ALTER TABLE ONLY public.favorite_doctors
    ADD CONSTRAINT uq_favorite UNIQUE (user_id, doctor_id);



