ALTER TABLE doctor_details
    ADD COLUMN fee BIGINT NOT NULL DEFAULT 0;

ALTER TABLE appointments
    ADD COLUMN fee BIGINT NOT NULL DEFAULT 0;

ALTER TABLE appointments
    ADD COLUMN payment_method VARCHAR(20) NOT NULL DEFAULT 'CASH';

ALTER TABLE appointments
    ADD CONSTRAINT chk_payment_method
        CHECK (payment_method IN ('CASH', 'ZALOPAY'));


CREATE TABLE public.transactions (
    id BIGINT NOT NULL,
    appointment_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    zp_trans_id VARCHAR(100),
    app_trans_id VARCHAR(100),
    payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    payment_date TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Auto-increment id
ALTER TABLE public.transactions
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Primary key
ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);

-- FK tới appointments (giao dịch thuộc về lịch khám nào)
ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk_transaction_appointment FOREIGN KEY (appointment_id)
    REFERENCES public.appointments(id)
    ON DELETE CASCADE;

-- Constraint: chỉ cho phép payment_status hợp lệ
ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT chk_payment_status CHECK (payment_status IN ('PENDING', 'SUCCESS', 'FAILED'));

ALTER TABLE public.notifications
DROP CONSTRAINT IF EXISTS notifications_type_check;

ALTER TABLE public.notifications
    ADD CONSTRAINT notifications_type_check
        CHECK (type IN (
            'APPOINTMENT_PENDING',
            'APPOINTMENT_CONFIRMED',
            'APPOINTMENT_CANCELLED',
            'APPOINTMENT_RESCHEDULED',
            'APPOINTMENT_REVIEW_REQUEST',
            'REMINDER',
            'NOTIFICATION_PAYMENT'
        ));


