CREATE TABLE public.medical_records (
    id BIGINT NOT NULL,
    record_code VARCHAR(20) UNIQUE,
    patient_name VARCHAR(100) NOT NULL,
    patient_age INT,
    patient_phone VARCHAR(20),
    diagnosis VARCHAR(255),
    symptoms TEXT,
    notes TEXT,
    doctor_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE ONLY public.medical_records
    ADD CONSTRAINT pk_medical_records PRIMARY KEY (id);

ALTER TABLE public.medical_records
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medical_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Thêm khóa ngoại tới Doctor
ALTER TABLE public.medical_records
    ADD CONSTRAINT fk_medical_records_doctor
        FOREIGN KEY (doctor_id)
            REFERENCES public.accounts(id)
            ON DELETE RESTRICT
            ON UPDATE CASCADE;

CREATE TABLE public.prescriptions (
    id BIGINT NOT NULL,
    medical_record_id BIGINT NOT NULL,
    medicine_name VARCHAR(100) NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    unit VARCHAR(50),
    dose VARCHAR(100),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Khóa chính
ALTER TABLE ONLY public.prescriptions
    ADD CONSTRAINT pk_prescriptions PRIMARY KEY (id);

-- IDENTITY (auto increment)
ALTER TABLE public.prescriptions
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prescriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Khóa ngoại tới bảng medical_records
ALTER TABLE public.prescriptions
    ADD CONSTRAINT fk_prescriptions_medical_record_id
        FOREIGN KEY (medical_record_id)
            REFERENCES public.medical_records(id)
            ON DELETE CASCADE
            ON UPDATE CASCADE;