--Create table Conversation_members
CREATE TABLE public.conversation_unreads (
    conversation_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    unread_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.conversation_unreads
    ADD CONSTRAINT pk_conversation_unreads PRIMARY KEY (conversation_id, account_id);

ALTER TABLE public.conversation_unreads
    ADD CONSTRAINT fk_conversation_unreads_conversation_id FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE CASCADE;

ALTER TABLE public.conversation_unreads
    ADD CONSTRAINT fk_conversation_unreads_account_id FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;

-- Create table for messages
CREATE TABLE public.messages (
    id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    message_type VARCHAR(20) NOT NULL CHECK (message_type IN ('MESSAGE', 'FILE', 'IMAGE', 'CALL')),
    message_content TEXT,
    file_url TEXT,
    file_name VARCHAR(255),
    file_size BIGINT,
    file_type VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.messages
    ADD CONSTRAINT pk_messages PRIMARY KEY (id);


ALTER TABLE public.messages
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

ALTER TABLE public.messages
    ADD CONSTRAINT fk_messages_conversation_id FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE CASCADE;

ALTER TABLE public.messages
    ADD CONSTRAINT fk_messages_account_id FOREIGN KEY (sender_id) REFERENCES public.accounts(id) ON DELETE CASCADE;

CREATE TABLE public.call_sessions (
    id BIGINT NOT NULL ,
    conversation_id BIGINT NOT NULL,
    caller_id BIGINT NOT NULL,
    call_type VARCHAR(10) NOT NULL CHECK (call_type IN ('AUDIO', 'VIDEO')),
    started_at TIMESTAMP(6),
    ended_at TIMESTAMP(6),
    status VARCHAR(20) DEFAULT 'ONGOING' CHECK (
        status IN ('ONGOING', 'CANCELLED', 'MISSED', 'REJECTED', 'ENDED')
    ),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.call_sessions
    ADD CONSTRAINT pk_call_sessions PRIMARY KEY (id);


ALTER TABLE public.call_sessions
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.call_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

ALTER TABLE public.call_sessions
    ADD CONSTRAINT fk_call_sessions_conversation_id FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE CASCADE;

ALTER TABLE public.call_sessions
    ADD CONSTRAINT fk_call_sessions_account_id FOREIGN KEY (caller_id) REFERENCES public.accounts(id) ON DELETE CASCADE;
