-- create-articles-table
CREATE TABLE public.articles (
    id BIGINT NOT NULL,
    content TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'PUBLIC'
        CHECK (status IN ('PUBLIC', 'PRIVATE')),
    user_id BIGINT NOT NULL,
    original_article_id BIGINT,
    vote_count INT DEFAULT 0,
    comment_count INT DEFAULT 0,
    share_count INT DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Tạo identity cho cột id
ALTER TABLE public.articles
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Khóa chính
ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);

-- Ràng buộc khóa ngoại: user_id -> accounts(id)
ALTER TABLE public.articles
    ADD CONSTRAINT fk_articles_user FOREIGN KEY (user_id)
        REFERENCES public.accounts(id) ON DELETE CASCADE;

-- Ràng buộc khóa ngoại: original_article_id -> articles(id)
ALTER TABLE public.articles
    ADD CONSTRAINT fk_articles_original FOREIGN KEY (original_article_id)
        REFERENCES public.articles(id) ON DELETE SET NULL;

-- create-article-votes-table
CREATE TABLE public.article_votes (
    id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reaction_type VARCHAR(20) NOT NULL
        CHECK (reaction_type IN ('LIKE', 'LOVE', 'HAHA', 'WOW', 'SAD', 'ANGRY')),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Identity
ALTER TABLE public.article_votes
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_votes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Khóa chính
ALTER TABLE ONLY public.article_votes
    ADD CONSTRAINT article_votes_pkey PRIMARY KEY (id);

-- FK: article_id -> articles(id)
ALTER TABLE public.article_votes
    ADD CONSTRAINT fk_votes_article FOREIGN KEY (article_id)
        REFERENCES public.articles(id) ON DELETE CASCADE;

-- FK: user_id -> accounts(id)
ALTER TABLE public.article_votes
    ADD CONSTRAINT fk_votes_user FOREIGN KEY (user_id)
        REFERENCES public.accounts(id) ON DELETE CASCADE;

-- Mỗi user chỉ 1 reaction cho 1 bài
ALTER TABLE public.article_votes
    ADD CONSTRAINT uq_votes_article_user UNIQUE (article_id, user_id);

-- create-article-comments-table
CREATE TABLE public.article_comments (
    id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    content TEXT,
    file_type VARCHAR(20) CHECK (file_type IN ('IMAGE','VIDEO','FILE')),
    file_url TEXT,
    vote_count INT DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Tạo identity cho cột id
ALTER TABLE public.article_comments
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Khóa chính
ALTER TABLE ONLY public.article_comments
    ADD CONSTRAINT article_comments_pkey PRIMARY KEY (id);

-- Ràng buộc khóa ngoại: article_id -> articles(id)
ALTER TABLE public.article_comments
    ADD CONSTRAINT fk_comment_article FOREIGN KEY (article_id)
        REFERENCES public.articles(id) ON DELETE CASCADE;

-- Ràng buộc khóa ngoại: user_id -> accounts(id)
ALTER TABLE public.article_comments
    ADD CONSTRAINT fk_comment_user FOREIGN KEY (user_id)
        REFERENCES public.accounts(id) ON DELETE CASCADE;

-- Ràng buộc khóa ngoại: parent_comment_id -> article_comments(id)
ALTER TABLE public.article_comments
    ADD CONSTRAINT fk_comment_parent FOREIGN KEY (parent_comment_id)
        REFERENCES public.article_comments(id) ON DELETE CASCADE;

-- create-article-media-table
CREATE TABLE public.article_medias (
    id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    file_type VARCHAR(20) NOT NULL CHECK (file_type IN ('IMAGE', 'VIDEO', 'FILE')),
    file_url TEXT NOT NULL,
    order_index INT DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Tạo identity cho cột id
ALTER TABLE public.article_medias
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_medias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Khóa chính
ALTER TABLE ONLY public.article_medias
    ADD CONSTRAINT article_media_pkey PRIMARY KEY (id);

-- Ràng buộc khóa ngoại: article_id -> articles(id)
ALTER TABLE public.article_medias
    ADD CONSTRAINT fk_media_article FOREIGN KEY (article_id)
        REFERENCES public.articles(id) ON DELETE CASCADE;

-- create-article-comments-votes-table
CREATE TABLE public.article_comment_votes (
    id BIGINT NOT NULL,
    comment_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reaction_type VARCHAR(20) NOT NULL
        CHECK (reaction_type IN ('LIKE', 'LOVE', 'HAHA', 'WOW', 'SAD', 'ANGRY')),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Tạo identity cho cột id
ALTER TABLE public.article_comment_votes
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_comment_votes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Khóa chính
ALTER TABLE ONLY public.article_comment_votes
    ADD CONSTRAINT article_comment_votes_pkey PRIMARY KEY (id);

-- FK: comment_id -> article_comments(id)
ALTER TABLE public.article_comment_votes
    ADD CONSTRAINT fk_comment_votes_comment FOREIGN KEY (comment_id)
        REFERENCES public.article_comments(id) ON DELETE CASCADE;

-- FK: user_id -> accounts(id)
ALTER TABLE public.article_comment_votes
    ADD CONSTRAINT fk_comment_votes_user FOREIGN KEY (user_id)
        REFERENCES public.accounts(id) ON DELETE CASCADE;

-- Mỗi user chỉ 1 reaction cho 1 comment
ALTER TABLE public.article_comment_votes
    ADD CONSTRAINT uq_comment_votes_user UNIQUE (comment_id, user_id);



