--create-accounts-table
CREATE TABLE public.accounts (
    id BIGINT NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL UNIQUE ,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.accounts
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);

--create-key-table
CREATE TABLE public.keys (
    id BIGINT NOT NULL,
    notification_key VARCHAR(255),
    refresh_token VARCHAR(512),
    user_id BIGINT UNIQUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.keys
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

ALTER TABLE ONLY public.keys
    ADD CONSTRAINT keys_pkey PRIMARY KEY (id);

--Them khoa ngoai cho bang Keys
ALTER TABLE public.keys
    ADD CONSTRAINT fk_keys_user_id FOREIGN KEY (user_id) REFERENCES public.accounts(id) ON DELETE CASCADE;

--Create table User_Detail
CREATE TABLE public.user_details (
    id BIGINT NOT NULL,
    gender VARCHAR(10) CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    date_of_birth DATE,
    avatar_url VARCHAR(255),
    phone VARCHAR(20),
    user_id BIGINT UNIQUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.user_details
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

ALTER TABLE ONLY public.user_details
    ADD CONSTRAINT user_details_pkey PRIMARY KEY (id);

--Them khoa ngoai cho bang User_Details
ALTER TABLE public.user_details
    ADD CONSTRAINT fk_user_details_user_id FOREIGN KEY (user_id) REFERENCES public.accounts(id) ON DELETE CASCADE;

--Create table Conversation
CREATE TABLE public.conversations (
    id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.conversations
    ADD CONSTRAINT pk_conversations PRIMARY KEY (id);

ALTER TABLE public.conversations
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

--Create table Conversation_members
CREATE TABLE public.conversation_members (
    conversation_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.conversation_members
    ADD CONSTRAINT pk_conversation_members PRIMARY KEY (conversation_id, account_id);

ALTER TABLE public.conversation_members
    ADD CONSTRAINT fk_conversation_members_conversation_id FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE CASCADE;

ALTER TABLE public.conversation_members
    ADD CONSTRAINT fk_conversation_members_account_id FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;

